name: HardishRespawn
main: xyz.drewcification.hardcorerespawn.HardcoreRespawn
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/drewc5131/hardishcorerespawn
author: drewcification
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
